Less1
ecotoyfounder/react-course-app pull request #1
Opened 2022-07-10 17:37 UTC by ecotoyfounder

Add less1 file

2022-07-10 18:06 UTC, AndreiSachuk requested changes
Надо дорабатывать

2022-07-10 18:06 UTC, AndreiSachuk commented on src/components/users.jsx
> +    const renderPhrase = (number, text) => {
что за текст ты сюда передаешь?

2022-07-10 18:06 UTC, AndreiSachuk commented on src/components/users.jsx
> +                <td>{user.qualities.map((item) => (
вынес вы в отдельный модуль

2022-07-10 18:06 UTC, AndreiSachuk commented on src/components/users.jsx
> +                <td>{user.rate}</td>
посмотри внимательно как оно отображается в таблице

2022-07-10 18:06 UTC, AndreiSachuk commented on src/components/users.jsx
> +            <table className="table">
зачем нам шапка таблицы, если все юзеры удалены?

2022-07-10 18:07 UTC, AndreiSachuk requested changes

2022-07-10 18:07 UTC, AndreiSachuk commented on src/components/users.jsx
> +        } else if (number % 10 === 2 || number % 10 === 3 || number % 10 === 4 && number > 1) {
И вот тут не хватает скобочек, на сколько я правильно понимаю

2022-07-10 19:56 UTC, ecotoyfounder reviewed
Fixed my errors

2022-07-10 20:11 UTC, ecotoyfounder reviewed
add some beauty

2022-07-11 17:00 UTC, AndreiSachuk requested changes

2022-07-11 17:00 UTC, AndreiSachuk commented on src/components/users.jsx
> +    let text = ""
ну вот объясни мне, для чего text вне метода?
для чего он пустой передается в метод?
Вернее он создан в скоупе, а в метод не передается?

2022-07-11 17:13 UTC, ecotoyfounder commented on src/components/users.jsx
> +    let text = ""
ну да, как г@вно в проруби) спишем это на вечер, но признаю, косяк

2022-07-11 18:00 UTC, AndreiSachuk approved these changes

2022-07-11 18:00 UTC, merged